name: ubuntu-latest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  ubuntu-latest-build:
    uses: ./.github/workflows/maven.yml
    with:
      os: ubuntu-latest